Hide `NavBar` when `BrandExplained` is in view
pif-network/pif-network pull request #166
Opened 2023-11-20 09:03 UTC by edmondwinston

2023-11-21 14:51 UTC, imsumoregn commented on lib/contexts/position-observer.tsx
> +});
Why is the `PositionObserver` observing a specific component state?

2023-11-21 17:05 UTC, edmondwinston commented on lib/contexts/position-observer.tsx
> +});
I think the logic to decide when to hide the nav should be placed where it is now because it can be quite messy if I try to just export the positions and calculate in the nav

2023-11-21 17:37 UTC, imsumoregn commented on lib/contexts/position-observer.tsx
> +});
Make sense. You can turn this into a pattern and write docs for it.

2023-11-21 17:38 UTC, imsumoregn commented on lib/contexts/position-observer.tsx
> +});
Also, make them friendly a bit, guess may come at the end of the year.

2023-11-22 05:03 UTC, imsumoregn requested changes

2023-11-22 05:03 UTC, imsumoregn commented on lib/contexts/position-observer.tsx
> +  }, [scrollY]);
Having `scrollY` as a dependency doesn't make much sense - well, it would be if you weren't using `scrollY` inside this handler, because its value is updated when the handler isn't.

2023-11-22 05:03 UTC, imsumoregn commented on lib/contexts/position-observer.tsx
> +  }, [handleScroll]);
`handleScroll` changes quite often because again, you are accessing `scrollY` inside it.

2023-11-22 05:03 UTC, imsumoregn commented on components/common/nav-bar.tsx
> +        navBar.shouldHide && 'hidden'
Please also add some simple animation when the bar is disappearing. 4s will review it later this week.

2023-11-23 16:40 UTC, edmondwinston commented on components/common/nav-bar.tsx
> +        navBar.shouldHide && 'hidden'
Added

2023-11-23 16:40 UTC, edmondwinston commented on lib/contexts/position-observer.tsx
> +  }, [handleScroll]);
Will fix this and the above in a separate PR

2023-11-24 21:14 UTC, imsumoregn approved these changes

2023-11-24 21:14 UTC, merged