Create user on `CompleteProfile` form submit
pif-network/pif-network pull request #170
Opened 2023-12-16 13:49 UTC by edmondwinston

2023-12-17 02:18 UTC, imsumoregn requested changes

2023-12-17 02:18 UTC, imsumoregn commented on app/(auth)/user/complete-profile/components/index.tsx
> +export * from './description-pack';
Keeping having to do this is not very ideal - what would be the solution if we take forward compatibility in to account?

2023-12-17 02:18 UTC, imsumoregn commented on app/(auth)/user/complete-profile/components/step-2-pack.tsx
> +      name="githubUrl"
Usually in bigger teams, there would be a centralised solution for these kind of things from day zero.

2023-12-17 02:18 UTC, imsumoregn commented on app/(auth)/user/complete-profile/page.tsx
> +import { api } from '~/lib/trpc/client';
Nit: Import order.

2023-12-17 02:18 UTC, imsumoregn commented on lib/trpc/server.ts
> +// export const rscApi = appRouter.createCaller({
What happened here?

2023-12-17 02:18 UTC, imsumoregn commented on package.json
> +    "next": "14.0.4",
For big version jump, let's have it in a separate PR next time, for the sake of reverting.

2023-12-17 02:18 UTC, imsumoregn commented on server/api/routers/user.ts
> +});
If you prefer to have the schema here, then the `formSchema` on the client could be inferred from the router output.
https://trpc.io/docs/client/vanilla/infer-types

2023-12-17 02:18 UTC, imsumoregn commented on server/db/schema.prisma
> +  name        String @unique @db.VarChar(25)
Not bad.

2023-12-17 04:35 UTC, edmondwinston commented on server/api/routers/user.ts
> +});
Issue created

2023-12-17 04:36 UTC, edmondwinston commented on package.json
> +    "next": "14.0.4",
yb

2023-12-17 04:37 UTC, edmondwinston commented on lib/trpc/server.ts
> +// export const rscApi = appRouter.createCaller({
The previous code worked because there was no context, but after adding db and auth, I can't put the context in here

2023-12-17 04:37 UTC, edmondwinston commented on lib/trpc/server.ts
> +// export const rscApi = appRouter.createCaller({
So I decided to delay the fixing until we actually need to use this

2023-12-17 04:39 UTC, edmondwinston commented on app/(auth)/user/complete-profile/components/index.tsx
> +export * from './description-pack';
Maybe to store those form parts in a map or something, created an issue

2023-12-17 04:40 UTC, edmondwinston commented on app/(auth)/user/complete-profile/components/step-2-pack.tsx
> +      name="githubUrl"
You mean having the keys extracted from the schema?

2023-12-17 17:20 UTC, imsumoregn commented on app/(auth)/user/complete-profile/components/index.tsx
> +export * from './description-pack';
Next milestone, then.

2023-12-17 17:21 UTC, imsumoregn commented on app/(auth)/user/complete-profile/components/step-2-pack.tsx
> +      name="githubUrl"
Could be - you can make decisions, just please do have reasons for them.

2023-12-20 09:13 UTC, imsumoregn approved these changes
Skipping failed deployment since we are not using `@ant-design/icons` anymore.

2023-12-20 09:13 UTC, merged